/**
 * Builds docs/internal-linking-report.md from the exported site.
 *
 * Unlike scripts/validate-content.mjs this never fails the build — it is a
 * diagnostic. Run it after `npm run build`.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'out');
const DOCS = join(ROOT, 'docs');

if (!existsSync(OUT)) {
  console.error('link-report: out/ not found — run `npm run build` first.');
  process.exit(1);
}
mkdirSync(DOCS, { recursive: true });

function walk(dir) {
  const found = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else if (full.endsWith('.html')) found.push(full);
  }
  return found;
}

const pagePath = (file) =>
  `/${file.slice(OUT.length + 1).split('\\').join('/').replace(/index\.html$/, '')}`;

const files = walk(OUT);
const pages = new Map();

// Anchors only — <img src> and asset references are not navigation.
const ANCHOR = /<a\b[^>]*href="(\/[^"]*)"[^>]*>([\s\S]*?)<\/a>/g;
const stripTags = (html) => html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();

for (const file of files) {
  const html = readFileSync(file, 'utf8');
  const path = pagePath(file);
  const links = [];
  let match;
  while ((match = ANCHOR.exec(html)) !== null) {
    const href = match[1].split('#')[0].split('?')[0];
    if (!href || href.startsWith('/_next/')) continue;
    links.push({ href, text: stripTags(match[2]).replace(/\s*\(opens.*$/, '') });
  }
  pages.set(path, { links, path });
}

const known = new Set(pages.keys());

/* inbound counts */
const inbound = new Map([...known].map((p) => [p, new Set()]));
const broken = new Map();
const anchorsByText = new Map();

for (const { path, links } of pages.values()) {
  for (const { href, text } of links) {
    if (href === path) continue;
    if (known.has(href)) inbound.get(href).add(path);
    else if (!href.endsWith('.xml') && !href.endsWith('.txt') && !href.endsWith('.png')) {
      if (!broken.has(href)) broken.set(href, new Set());
      broken.get(href).add(path);
    }
    const key = text.toLowerCase();
    if (!key || key.length < 3) continue;
    if (!anchorsByText.has(key)) anchorsByText.set(key, new Set());
    anchorsByText.get(key).add(href);
  }
}

/* click depth from the homepage */
const depth = new Map([['/', 0]]);
let frontier = ['/'];
while (frontier.length > 0) {
  const next = [];
  for (const path of frontier) {
    for (const { href } of pages.get(path)?.links ?? []) {
      if (known.has(href) && !depth.has(href)) {
        depth.set(href, depth.get(path) + 1);
        next.push(href);
      }
    }
  }
  frontier = next;
}

const contentPages = [...known].filter((p) => p !== '/' && !p.startsWith('/404'));
const orphans = contentPages.filter((p) => (inbound.get(p)?.size ?? 0) === 0);
const thin = contentPages.filter((p) => {
  const count = inbound.get(p)?.size ?? 0;
  return count > 0 && count < 3;
});
const unreachable = contentPages.filter((p) => !depth.has(p));
const deep = contentPages.filter((p) => (depth.get(p) ?? 0) > 3);
const ambiguous = [...anchorsByText.entries()].filter(([, targets]) => targets.size > 1);

const articlePages = contentPages.filter((p) => /^\/blog\/[^/]+\/$/.test(p));
const appPages = contentPages.filter((p) => /^\/apps\/[^/]+\/$/.test(p));

const rank = (list) =>
  list
    .map((p) => ({ path: p, count: inbound.get(p)?.size ?? 0, depth: depth.get(p) ?? '—' }))
    .sort((a, b) => b.count - a.count || a.path.localeCompare(b.path));

const lines = [
  '# Internal linking report',
  '',
  '_Generated by `node scripts/link-report.mjs` from the exported `out/` directory._',
  '_Diagnostic only — this script never fails the build._',
  '',
  '## Summary',
  '',
  `- **${pages.size}** exported pages`,
  `- **${appPages.length}** app pages, **${articlePages.length}** articles`,
  `- **${broken.size}** broken internal links`,
  `- **${orphans.length}** orphan pages (no inbound links)`,
  `- **${thin.length}** thinly linked pages (1–2 inbound links)`,
  `- **${unreachable.length}** pages unreachable by crawling from the homepage`,
  `- **${deep.length}** pages more than 3 clicks deep`,
  `- **${ambiguous.length}** anchor texts pointing at more than one destination`,
  '',
];

const section = (title, body) => {
  lines.push(`## ${title}`, '');
  if (body.length === 0) lines.push('None.', '');
  else lines.push(...body, '');
};

section(
  'Broken internal links',
  [...broken.entries()].map(([href, from]) => `- \`${href}\` — linked from ${[...from].join(', ')}`)
);

section('Orphan pages', orphans.map((p) => `- \`${p}\``));

section(
  'Unreachable from the homepage',
  unreachable.map((p) => `- \`${p}\``)
);

section(
  'Pages more than 3 clicks deep',
  deep.map((p) => `- \`${p}\` — depth ${depth.get(p)}`)
);

section(
  'Thinly linked pages (1–2 inbound)',
  thin.map((p) => `- \`${p}\` — ${inbound.get(p).size} inbound`)
);

section(
  'Ambiguous anchor text',
  ambiguous
    .slice(0, 40)
    .map(([text, targets]) => `- "${text}" → ${[...targets].map((t) => `\`${t}\``).join(', ')}`)
);

lines.push('## Inbound links by page', '', '| Page | Inbound | Depth |', '| --- | --- | --- |');
for (const row of rank(contentPages)) {
  lines.push(`| \`${row.path}\` | ${row.count} | ${row.depth} |`);
}
lines.push('');

writeFileSync(join(DOCS, 'internal-linking-report.md'), lines.join('\n'), 'utf8');

console.log(
  `link report: ${pages.size} pages, ${broken.size} broken, ${orphans.length} orphans, ${thin.length} thin`
);
console.log('  docs/internal-linking-report.md');
